// ALERT TYPES 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// CONFIRM MODAL TYPES 
export const SET_MODAL = 'SET_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

// ITERATING MODAL TYPES
export const SET_ITERATING_MODAL = 'SET_ITERATING_MODAL';
export const REMOVE_ITERATING_MODAL = 'REMOVE_ITERATING_MODAL';

// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

// USER TYPES 
export const FETCH_USERNAMES = 'FETCH_USERNAMES';
export const UPDATE_PROFILE_PIC = 'UPDATE_PROFILE_PIC';
export const USER_ERROR = 'USER_ERROR';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const FOLLOW_PROFILE = 'FOLLOW_PROFILE';
export const UNFOLLOW_PROFILE = 'UNFOLLOW_PROFILE';
export const SET_FOLLOWING = 'SET_FOLLOWING';
export const UNSET_FOLLOWING = 'UNSET_FOLLOWING';

// POST TYPES
export const CREATE_POST = 'CREATE_POST';
export const POST_ERROR = 'POST_ERROR';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const FETCH_FOLLOWING_POSTS = 'FETCH_FOLLOWING_POSTS';
export const FETCH_MY_POSTS = 'FETCH_MY_POSTS';
export const FETCH_USER_PROFILE_POSTS = 'FETCH_USER_PROFILE_POSTS';
export const FETCH_ADOPTION_POSTS = 'FETCH_ADOPTION_POSTS';

// LIKE TYPES [just to see who all has liked your post]
export const FETCH_LIKES = 'FETCH_LIKES';
export const LIKE_ERROR = 'LIKE_ERROR';
export const REMOVE_LIKES = 'REMOVE_LIKES';

// CHAT TYPES
export const SET_CHAT = 'SET_CHAT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_CHAT = 'CLEAR_CHAT';
export const CHAT_ERROR = 'CHAT_ERROR';
export const FETCH_CHAT_DATA = 'FETCH_CHAT_DATA';
export const FETCH_ALL_CHAT_MESSAGES = 'FETCH_ALL_CHAT_MESSAGES';
export const CREATE_ROOM = 'CREATE_ROOM';
export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

// NOTIFICATION TYPES
export const NOTIFY_USER = 'NOTIFY_USER';
export const NOTIFY_ERROR = 'NOTIFY_ERROR';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const SET_HAS_VIEWED_NOTIFICATIONS = 'SET_HAS_VIEWED_NOTIFICATIONS';
