// ALERT TYPES 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// MODAL TYPES 
export const SET_MODAL = 'SET_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

// USER TYPES 
export const FETCH_USERNAMES = 'FETCH_USERNAMES';
export const USER_ERROR = 'USER_ERROR';

// PROFILE TYPES
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// POST TYPES
export const CREATE_POST = 'CREATE_POST';
export const POST_ERROR = 'POST_ERROR';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';